parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: tang_sf
    database_user: root
    database_password: '111111'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 71476a10534295610b999d451ad1772be7
    database_path: null
