acme_study_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeStudyBundle:Default:index }
    
random:
    path:       /random/{limit}
    defaults:  { _controller: AcmeStudyBundle:Random:index }
